name: ffmpeg build

on:
  push:

jobs:
  ffmpeg:
    name: "mingw-w64-x86_64 ffmpeg build"
    runs-on: windows-latest
    timeout-minutes: 960
    steps:
      - name: Checkout sunshine-prebuilt
        uses: actions/checkout@v2

      - name: Checkout media-autobuild_suite
        uses: actions/checkout@v2
        with:
          repository: m-ab-s/media-autobuild_suite
          path: media-autobuild_suite

      - name: Cache msys64
        id: cache-msys64
        uses: actions/cache@v2
        with:
          path: media-autobuild_suite/msys64
          key: ${{ runner.os }}-msys64

      - name: Copy sunshine-prebuilt config files
        shell: pwsh
        run: cp build/*.* media-autobuild_suite/build/

      - name: Replace do_prompt
        shell: pwsh
        working-directory: media-autobuild_suite
        run: sed -i 's/do_prompt /echo /g' build/media-suite_helper.sh build/media-suite_compile.sh
      
      - name: Compile the suite
        shell: cmd
        working-directory: media-autobuild_suite
        run: media-autobuild_suite.bat

      - name: Create pre-compiled folder
        shell: cmd
        run: scripts\create-pre-compiled.bat

      - name: Create pre-compiled.zip
        shell: pwsh
        run: Compress-Archive -Path pre-compiled\* -DestinationPath pre-compiled.zip

      - name: Upload pre-compiled.zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: pre-compiled.zip
          path: pre-compiled.zip